version: '3'

networks:
  webapp:


services:

  nginx:
    image: nginx:stable-alpine
    container_name: sisviansa_nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes:
      - ./data/:/var/www/html
      - ./data/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./data/docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - mariadb
      - vue
    networks:
      - webapp

  php:
    build:
      context: ./data/BackEnd
      dockerfile: Dockerfile
    container_name: sisviansa_php
    volumes:
      - ./data/BackEnd/:/var/www/html/BackEnd/
    ports:
      - "9000:9000"
    networks:
      - webapp

  mariadb:
    image: mariadb
    container_name: sisviansa_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "prueba"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "12345"
    volumes:
      - ./data/mariadb/:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webapp

  vue:
    container_name: sisviansa_vue
    build:
      context: ./data/FrontEnd
      dockerfile: Dockerfile
    volumes:
      - './data/FrontEnd:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
